name: mobile_engineering_playground

publish_to: none

environment:
  sdk: ^3.12.0

workspace:
  - apps/customer_app
  - packages/auth
  - packages/catalog
  - packages/checkout
  - packages/core
  - packages/design_system
  - packages/home
  - packages/navigation
  - packages/network
  - packages/observability
  - packages/config
  - packages/experimental_home

dev_dependencies:
  melos: ^7.8.2

melos:
  scripts:
    test:
      run: flutter test
      packageFilters:
        dirExists: test