name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  flutter:
    name: Flutter

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.44.1

      - name: Install Melos
        run: dart pub global activate melos

      - name: Bootstrap Workspace
        run: melos bootstrap
      
      - name: Analyze Workspace
        run: melos exec -- flutter analyze
      
      - name: Run Package Tests
        run: melos exec --dir-exists=test -- flutter test
      

  backend:
    name: Backend

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run build